[package]
name = "duero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
tokio = "1.35.0"
cranelift-jit = "0.102.1"
clap = { version = "4.4.11", features = ["derive"] }
